INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (11, 55, '11', 'Aceh (NAD)');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (12, 55, '12', 'Sumatera Utara');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (13, 55, '13', 'Sumatera Barat');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (14, 55, '14', 'Riau');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (15, 55, '15', 'Jambi');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (16, 55, '16', 'Sumatera Selatan');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (17, 55, '17', 'Bengkulu');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (18, 55, '18', 'Lampung');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (19, 55, '19', 'Kepulauan Bangka Belitung');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (21, 55, '21', 'Kepulauan Riau');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (31, 55, '31', 'DKI Jakarta');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (32, 55, '32', 'Jawa Barat');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (33, 55, '33', 'Jawa Tengah');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (34, 55, '34', 'DI Yogyakarta');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (35, 55, '35', 'Jawa Timur');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (36, 55, '36', 'Banten');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (51, 55, '51', 'Bali');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (52, 55, '52', 'Nusa Tenggara Barat (NTB)');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (53, 55, '53', 'Nusa Tenggara Timur (NTT)');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (61, 55, '61', 'Kalimantan Barat');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (62, 55, '62', 'Kalimantan Tengah');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (63, 55, '63', 'Kalimantan Selatan');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (64, 55, '64', 'Kalimantan Timur');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (65, 55, '65', 'Kalimantan Utara');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (71, 55, '71', 'Sulawesi Utara');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (72, 55, '72', 'Sulawesi Tengah');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (73, 55, '73', 'Sulawesi Selatan');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (74, 55, '74', 'Sulawesi Tenggara');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (75, 55, '75', 'Gorontalo');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (76, 55, '76', 'Sulawesi Barat');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (81, 55, '81', 'Maluku');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (82, 55, '82', 'Maluku Utara');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (91, 55, '91', 'Papua');
INSERT INTO `provinces` (`id`, `parent_id`, `code`, `name`) VALUES (92, 55, '92', 'Papua Barat');
